### ISSUE TITLE
It doesn't work with KiCad version 8 for me

### ISSUE THREAD

**Issue by wiserst** [yaqwsx/PcbDraw#162]
I used the same startup script as in KiCad version 7.
Here is an extract from the running script:

D:\Projects\PCB_designs\KiCad\Projects\LINET\W240228 - MIC Amp\W240228.01>D:\Renda\Documents\KiCad\8.0\3rdparty\Python311\Scripts\pcbdraw.exe plot "D:\Projects\PCB_designs\KiCad\Projects\LINET\W240228 - MIC Amp\W240228.01\W240228.01.kicad_pcb" "D:\Projects\PCB_designs\KiCad\Projects\LINET\W240228 - MIC Amp\W240228.01\Documentation\W240228.01(PCB_Bot).png" --no-components --style D:\Projects\PCB_designs\KiCad\__3rdparty_8.0\plugins\ProjectReleaser\wiser-blue-enig.json --side back --dpi 800
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Renda\Documents\KiCad\8.0\3rdparty\Python311\Scripts\pcbdraw.exe\__main__.py", line 4, in <module>
  File "D:\Renda\Documents\KiCad\8.0\3rdparty\Python311\site-packages\pcbdraw\ui.py", line 15, in <module>
    from .populate import populate
  File "D:\Renda\Documents\KiCad\8.0\3rdparty\Python311\site-packages\pcbdraw\populate.py", line 16, in <module>
    from mistune.plugins.table import plugin_table # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'plugin_table' from 'mistune.plugins.table' (D:\Renda\Documents\KiCad\8.0\3rdparty\Python311\site-packages\mistune\plugins\table.py)

**Comment by yaqwsx** [comment]
Somehow, during upgrade, PIP managed to mismatch version of the mistune library. We require https://github.com/yaqwsx/PcbDraw/blob/a748a8ed32e5c37aa7517c264f6daf78b4c31bec/setup.py#L29C9-L29C35, but it seems that you have version 3 installed.

**Comment by wiserst** [comment]
I installed PcbDraw via KiCad 8.0 command line - pip install PcbDraw
Can you please advise me what to do? Thank you.

**Comment by smkent** [comment]
https://github.com/yaqwsx/PcbDraw/pull/166 should resolve this.

**Comment by wiserst** [comment]
It still doesn't work for me. It will draw a small square in png.
[exam.zip](https://github.com/yaqwsx/PcbDraw/files/14900277/exam.zip)

**Comment by yaqwsx** [comment]
Thanks for the reports. The original `plugin_table` import failure is resolved in PcbDraw 1.2.0, which migrated Populate to the Mistune 3 API. I confirmed that PcbDraw 1.2.0 starts successfully with Mistune 3 and exposes the CLI normally.

Please upgrade with:

```bash
python -m pip install --upgrade "pcbdraw>=1.2.0"
```

PcbDraw supports the two latest KiCad major releases, currently KiCad 9 and KiCad 10; KiCad 8 is no longer supported.

Closing as fixed in PcbDraw 1.2.0. If the problem persists after upgrading on KiCad 9 or 10, please reopen this issue and include the exact command, full traceback, output of `pcbdraw --version`, KiCad version, Python version, and installed Mistune version.
